### ISSUE TITLE
Can't require() the dist version

### ISSUE THREAD

**Issue by wagenaartje** [wagenaartje/neataptic#1]
I have been setting up mocha tests lately, and I want to run the tests on the distributed version ofcourse. However, when doing `require('../dist/neataptic.js');` an empty object is returned. It works fine when running the tests on `require('../src/neataptic.js');`. Could someone lend me a helping hand?

**Comment by jocooler** [comment]
Was gynaptic renamed neataptic? And is this issue still open?

**Comment by wagenaartje** [comment]
@jocooler oops, the issue still exists. I changed it to Neataptic because it sounded better and because the library uses the NEAT algorithm. I just updated the issue!

**Comment by jocooler** [comment]
Thanks! It's not what I thought the problem might be and I'm not familiar with mocha, so not sure I'll be able to add anything, but I'll do some mocha reading and have a look. I found this project from Synaptic and looks like you've got some great stuff going on here.

**Comment by makryl** [comment]
Webpack doesn't exports anything by default. You should use `library` and `libraryTarget` options in webpack config, output section.
```
output: {
    ...
    library: 'neataptic',
    libraryTarget: 'umd'
}
```
`umd` is universal way for exporting, webpack will make all magic as you have in `neataptic.js` for CommonJS/AMD/Node.js/Browser.
https://webpack.js.org/configuration/output/#output-library

**Comment by wagenaartje** [comment]
Thanks a bunch! Got it all up and running in https://github.com/wagenaartje/neataptic/commit/77923c184b48e74feee8484a062cb422aff50adf
