### ISSUE TITLE
network.js.mutate: case mutation.ADD_BACK_CONN includes output nodes as connection input

### ISSUE THREAD

**Issue by bernard01** [wagenaartje/neataptic#102]
network.js
"version": "1.4.7"

mutate: function (method) {

  ....

      case mutation.ADD_BACK_CONN:
        // Create an array of all uncreated (backfed) connections
        var available = [];
        for (i = this.input; i < this.nodes.length; i++) {// ###### includes output node1 as connection input

This should lead to crashes further down the line.
I don't know whether this code is actually executed, but it looks like this could be a bug.

So we could limit the iteration to this.nodes.length - outputCount to avoid running into the outputs.

**Comment by wagenaartje** [comment]
Hmmm good point. It should not cause any crashes because these connections actually work, but I just realized that these connections will never be backpropagated correctly. I'll investigate it.

**Comment by bernard01** [comment]
I think this should be closed. I believe it is intended and good to have an output node as connection input. I was wrong there.
