### ISSUE TITLE
Question from a neural newbie.

### ISSUE THREAD

**Issue by imageschool** [wagenaartje/neataptic#127]
Hi, I am trying to use MLP to classify images into 5 different labels with Neataptic.js .
Downloaded 1000 images per each class (5000 in total) and resized all of them to 250X250 pixels.

I understand that all images need to be converted into 1D integer array to be the training set, ( and their classes ), then they also need to be normalised so they all lie between 0 and 1. 
However, I am not sure which way is the best in order to achieve this...

My issues are below, help would be really appreciated, sorry for dumb question.

1. Do images also need to be in grey-scale ? ( Otherwise, I think the image cannot be imported as 1D array )

2. Is 250 X 250 too big for this kind of train & testing ? ( If then how much should I reduce it ? )

3. To have an okay accuracy (> 80%) , how many images should I use for training ?  How long do you think it will take to train ?

4. What is the best way to read all these images into an actual neataptic [mytrainingset](https://wagenaartje.github.io/neataptic/docs/tutorials/training/) ?

What I thought is, read all the images in a certain label folder (1000), using python, then convert them into grey-scale & normalise. Then export these values into a text file then read it back on my web application. (It seems like a super bad idea to me..............)
 
Thank you very much for reading T.T

**Comment by dan-ryan** [comment]
"Do images also need to be in grey-scale ?"
They don't need to be greyscale but it is a lot less input and therefore quicker to train. So if you don't need colour then use greyscale.

"Is 250 X 250 too big for this kind of train & testing"
I would do them as small as possible to help with training speed. So it really depends on what level of detail you need. But 250 px sounds fine.

"how many images should I use for training ?"
Depends but try thousands.

**Comment by imageschool** [comment]
Thank you very much, just have seen this now :-] 👍
