### ISSUE TITLE
How to define output for evolve without target in game.

### ISSUE THREAD

**Issue by AZE38** [wagenaartje/neataptic#152]
hi, i want to train a network with evolve, i dont have output target, i just want to take the "better" network ,with my "condtion" in game -> "create-news and mutate" from this network ! I can do this ? if yes, how ? ^^ ( sry for my english..)

thx !

**Comment by AZE38** [comment]
beacause all of i have seen, i have to define 

var trainingSet = [
    { input: [0,0], output: [0] },
    { input: [0,1], output: [1] },
    { input: [1,0], output: [1] },
    { input: [1,1], output: [0] }
  ];


But i have juste one input [0...,i,.....n], who change in each "FPS" , and no "output"... so i want to "decomposed" the training, and select each "better" for my next generation.

**Comment by AZE38** [comment]
oohhhh.... is juste methods.selection.TOURNAMENT ?

Sry ^^

**Comment by AZE38** [comment]
hoo..i just must to do my own selection ->crossover->mutation .... from all of my starting network ? and stop when i m happy.

**Comment by AZE38** [comment]
sry for useless post ^^

**Comment by rhysstubbs** [comment]
@AZE38 please close the issue if this is resolved.
