### ISSUE TITLE
NEAT wiki page needs an update

### ISSUE THREAD

**Issue by zammbi** [wagenaartje/neataptic#16]
I'm trying to get my head around doing a more advanced example in NEAT. 

I have been looking at the source code of the agario-ai example. I see it using the method `neat.sort()` which the wiki page says "Should not be called manually". It also uses methods "neat.mutate()", "neat.getOffspring()" and "neat.population" which are not listed in the wiki page. 

For advance examples should we be going down the agario-ai path or should we be using the fitness function? 
https://github.com/wagenaartje/neataptic/wiki/NEAT

**Comment by wagenaartje** [comment]
Going down the 'agario-ai path' depends on how you want to test your population. The reason I did not use the built-in `evolve()` function for the agario-io example is because I wanted to test the genomes synchronously, while the `evolve()` function tests them one-by-one. 

I'll update the wiki soon so it includes all the missing functions and variables, and i'll extend the info on the functions a bit.

**Comment by zammbi** [comment]
I went down the 'agario-ai path', I think I got it working for the most part. I've found the scoring system is hard to get right. 
Oh, should the `activate` function be returning numbers outside 0 to 1? It has been returning negative numbers and numbers higher than 1.

**Comment by wagenaartje** [comment]
The scoring system is indeed hard to get right.

The activate function can definitely output numbersoutside 0 to 1. That is because not all [activation functions] have a range of `(0,1)`. The ranges of a lot of activation functions can be found [here](https://en.wikipedia.org/wiki/Activation_function). You can also change the allowed activation functions in `methods/mutation.js -> MOD_ACTIVATION.allowed`.

Another something I could implement to make sure the output is always normalised is to disable the mutation of activation of output nodes, should I make an option for this? I'm going to edit the wiki now btw.

**Comment by zammbi** [comment]
I'm all new to this, but I have spent my weekend learning and find this stuff very interesting. 

"should I make an option for this"
I think it would help me, but maybe I'm doing this wrong. 

Currently, I'm a little stuck, my model avoids a negative score, it can get a positive score but gets stuck on a score of 0 the more it learns. But probably a mistake I've done somewhere...

**Comment by wagenaartje** [comment]
I'll make some option for it soon.

About the getting stuck, what kind of problem are you letting your genomes solve? If you really get stuck with the scoring, feel free to make a seperate issue or mail me wagenaartje@protonmail.com

**Comment by zammbi** [comment]
Thanks for the wiki update, that helps a lot. Just so you know there are a few spelling mistakes on there. 
You might want to talk about the activate function on the NEAT page too. 

"I'll make some option for it soon."
Great. I think it will help. So I don't have to train my model to avoid values outside 0-1. 

"what kind of problem are you letting your genomes solve?"
Currently seeing if I can make it make money on a market. Found some history data to train it on.

"feel free to make a seperate issue or mail me"
Thanks for the offer. I think I got my model to continue working. It seems to be working now :)

**Comment by wagenaartje** [comment]
I made an option that disables the mutation of activation functions of output nodes. See it [here](https://github.com/wagenaartje/neataptic/blob/master/src/methods/mutation.js#L39). Commit https://github.com/wagenaartje/neataptic/commit/e94de6438a0363c6d564e337846c463ed9b1e697

**Comment by zammbi** [comment]
Great, can you show an example piece of code on how I'm meant to use it?

**Comment by wagenaartje** [comment]
I've added it here: https://github.com/wagenaartje/neataptic/wiki/Mutation#config

**Comment by zammbi** [comment]
Great, I'll give it a try tonight.

**Comment by zammbi** [comment]
@wagenaartje I gave it a try and it doesn't seem to be working. The output values from `activate` are not 0-1. I even tried manually changed the code. Am I missing something?

**Comment by wagenaartje** [comment]
@zammbi I just debugged it, I failed to make an exception for when there were no nodes to mutate the activation function from. I just added these lines:

```js
if(!method.mutateOutput && this.input + this.output == this.nodes.length){
  if(Config.warnings) console.warn('No nodes that allow mutation of activation function');
    break;
}
```

So should be fixed as of https://github.com/wagenaartje/neataptic/commit/e4cfbfa83c448a12f882c65195d8f66ccb7352dd

**Comment by zammbi** [comment]
@wagenaartje Yes, that fixed it. 
But I've now simplified my model to take advantage of the negative numbers :P 
I've combined the two outputs.
Is there an option to only output -1 to 1?

**Comment by wagenaartje** [comment]
@zammbi also a good solution :)

Yes, but this means setting the output nodes to have a different activation function. There are multiple [activation functions](https://github.com/wagenaartje/neataptic/wiki/Activation) in the range of `-1` to `1`, but I think `Methods.Activation.BIPOLAR_SIGMOID` is best for you!

PS: I will edit the activation wiki to include the ranges soon

**Comment by zammbi** [comment]
Ah this is now starting to make sense.

**Comment by zammbi** [comment]
@wagenaartje I see Wiki has range values:
https://en.wikipedia.org/wiki/Activation_function

Looks like I will keep with the other activation functions because the ones that just do -1 to 1 are just not working for my model. It might be because I'm needing small numbers.
