### ISSUE TITLE
Methods.Mutation.ALL breaks evolution 

### ISSUE THREAD

**Issue by zammbi** [wagenaartje/neataptic#19]
When using `Methods.Mutation.ALL`, it would break evolution and will never increase the nodes and connections. 

```
var neat = new Neat(3, 1, null, {
	mutation: [
		Methods.Mutation.ALL
  ]
});
```

Example here: 
https://jsfiddle.net/qjh2ecux/

**Comment by wagenaartje** [comment]
You should not supply it in a list. Methods.Mutation.ALL is a list itself, so

mutation: Methods.Mutation.ALL
