### ISSUE TITLE
Evolve does not stop after the specified generation

### ISSUE THREAD

**Issue by AWiryaman** [wagenaartje/neataptic#22]
I ran evolve on a data set with error set to 0.004 and generation set to 1000. Evolution did not stop running until after generation 11100. I'm not actually sure why it decided to stop at that point as the error was not lower than the specified 0.004

**Comment by wagenaartje** [comment]
Hi! I just tested it here: https://jsfiddle.net/669onmgn/ and it seems to work fine. Are you sure you are specifying `iterations` (not `generations`)? 

If you did by accident, should I change the `iterations` option to `generations`?

**Comment by AWiryaman** [comment]
I did do generations and not iterations. I was using the code given in Evolution 101 in the wiki which uses generations. So, I think it should be changed so that the usage is consistent between the wiki and the actual code.

**Comment by wagenaartje** [comment]
Sorry, my bad, I changed it. I also just noticed that the `evolve()` function returns the amount of `generations` (instead of iterations), I will make the usage consistent soon.
