### ISSUE TITLE
network.train(...) iterations stop at random points

### ISSUE THREAD

**Issue by kmui2** [wagenaartje/neataptic#24]
I'm trying to figure out why when I run network.train(...) with the options below (including the fact that I commented the error), the iterations randomly stop at a point between the 190th iteration and 250th iteration. Is there a simple solution to having it run all 1000 iterations?

![image](https://cloud.githubusercontent.com/assets/17896701/26532197/f2c2fdb0-43bf-11e7-8969-5af9240cbf09.png)

Using this cdn for the script: <script src="https://wagenaartje.github.io/neataptic/cdn/neataptic.js"></script>

const training_options = {
  log: 10,
  // error: 0.03,
  iterations: 1000,
  rate: 0.3
}

**Comment by wagenaartje** [comment]
Hi! The 'iterations' variable is a maximum: the training will only run for this amount of iterations if the target error has been reached.

If you dont pass on a target error to the training options, then te default value is used - I think that is 0.005. So your training will run untill that error is reached.

If you want to run training for the full 1000 iterations, specify a really low error (eg. 0.000000001). 

0 as target error wont work fyi, but ill update this soon.

Hope thus helps, written from mobile.

**Comment by wagenaartje** [comment]
"Has been reached" should be "had not een reached" in the first paragraph

**Comment by wagenaartje** [comment]
From now on, certain options must be specified.  https://github.com/wagenaartje/neataptic/commit/38f87af8f78d65ea1cba2c72f93fac6fb77b58ea
