### ISSUE TITLE
NEAT wiki mistakes

### ISSUE THREAD

**Issue by zammbi** [wagenaartje/neataptic#29]
Noticed two issues on the NEAT doc page (https://wagenaartje.github.io/neataptic/docs/neat/)

"selection
Sets the allowed selection methods used in the evolutionary process. Must be an array. Must be an array (e.g. [Selection.FITNESS_PROPORTIONATE]). Default is FITNESS_PROPORTIONATE."

It's not an array (it crashes if you try). 

"equal
If you want to start the algorithm from a specific network, specify your network here."

This description is for the "network" option.

**Comment by wagenaartje** [comment]
I updated the documentation https://github.com/wagenaartje/neataptic/commit/6bc2c34105837c196b8a96a92ec959b2ad8a01a1. I also recommended you to use a `clear` option before, but I realised it only existed for the built-in `network.evolve()` function. So I added this option to the NEAT constructor.
