### ISSUE TITLE
tutorial problem

### ISSUE THREAD

**Issue by momire** [wagenaartje/neataptic#31]
Hello. I am a beginner who is touched by the convenience of neataptic. :)

In the Training, Evolution section of the tutorial,

```
yourNetwork.train(yourData, yourOptions);
YourNetwork.evolve (yourData, yourOptions);
```

It says that the default values are preset, but the tutorial does not explained how to use the default values.

```
yourNetwork.train(yourData, {});
YourNetwork.evolve (yourData, {});
```

I've found that this is not a problem when I write this code. It can be quite confusing for beginners like me. (I honestly do not know it's right or wrong to write code like this.) but I have not seen a library that is kind enough for beginners as much as this library.

**Comment by wagenaartje** [comment]
Hi! Thanks for checking out Neataptic. I have changed the training and evolution tutorials. Let me know if you think anything is missing/wrong! 

Along with a few other things, I have added:

> If you want to use the default options, you can either pass an empty object or
just dismiss the whole second argument:
> ```javascript
> myNetwork.evolve(trainingSet, {});
>// or
> myNetwork.evolve(trainingSet);
>```
>
> The default value will be used for any option that is not explicitly provided
in the options object.
