### ISSUE TITLE
should SWAP_NODES consider the mutateOutput options?

### ISSUE THREAD

**Issue by kiomac** [wagenaartje/neataptic#35]
After turning off the mutations on the output with:
```js
MOD_ACTIVATION.mutateOutput = false;
```
should we protect the output node when trying a SWAP_NODES mutation?

After updating with 7e75cd98802a2b5425386bde86e5a2d27b2f90fd commit, I found myself with broken outputs so I disabled SWAP_NODES to continue.

Perhaps adding a ```SWAP_NODES.mutateOutput```?

**Comment by wagenaartje** [comment]
> Perhaps adding a SWAP_NODES.mutateOutput?

That is an excellent idea. I'll add it somewhere today.

> I found myself with broken outputs 

You just mean that suddenly their activation function changed (and thus might not always have between `0` and `1`?)

**Comment by wagenaartje** [comment]
Option added as of https://github.com/wagenaartje/neataptic/commit/eab97ccd834dfd9cdf660a70f77260f1109f5489. No new version required. Included in the documentation here: https://wagenaartje.github.io/neataptic/docs/methods/mutation/.

**Comment by kiomac** [comment]
> That is an excellent idea. I'll add it somewhere today.

That was fast! Thanks a lot!

> You just mean that suddenly their activation function changed (and thus might not always have between 0 and 1?)

Exactly! The squash in the output node was being replaced. I'm still not entirely sure this is the appropriate thing to do, but at least I'm getting faster higher scores when running many unsupervised iterations; compared with a manual output normalization and letting the network mutate the activation function at will:

```js
var out0 = this.brain.activate(inputs)[0];

// rely on a SINUSOID output function will always return values from -1 to 1.
// or,

out0  = out0 < -1 ? -1 : out0 > 1 ? 1 : out0;
```
