### ISSUE TITLE
LSTM example not working

### ISSUE THREAD

**Issue by delaneyj** [wagenaartje/neataptic#38]
[Link in LSTM docs](https://jsfiddle.net/wagenaartje/k23zbf0f/1/) has no output and following errors in console

```
neataptic.js Failed to load resource: the server responded with a status of 404 (Not Found)
fiddle.jshell.net/wagenaartje/k23zbf0f/1/show/:54 Uncaught ReferenceError: neataptic is not defined
```

**Comment by wagenaartje** [comment]
Thanks for mentioning it! It used an outdated link to the `neataptic.js` file. I updated the JSFiddle and the link on the documentation.

[Have a look!](https://jsfiddle.net/k23zbf0f/8/)
