### ISSUE TITLE
Network crossover bug

### ISSUE THREAD

**Issue by tbarross** [wagenaartje/neataptic#4]
seems today i am getting lucky (or unlucky) getting this odd behaviours

![capture](https://cloud.githubusercontent.com/assets/11909606/25086872/05d5480e-2363-11e7-9f0d-638c4dc72b09.JPG)
![capture2](https://cloud.githubusercontent.com/assets/11909606/25086873/05da7716-2363-11e7-9487-25878808e037.JPG)

this might be because i am running the new mutations on a Neat Object.

**Comment by wagenaartje** [comment]
See issue https://github.com/wagenaartje/neataptic/issues/3. Will be updated asap!

**Comment by wagenaartje** [comment]
This has been added in the latest update (https://github.com/wagenaartje/neataptic/commit/6f08f82fc1bb343473b353691a75861fa113a710)!
