### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by tracycollins** [wagenaartje/neataptic#40]
Running version 1.3.0, the XOR evolve example has the error:

> (node:13051) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'FFW' of undefined
(node:13051) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Seems like setting the Methods.mutation.FFW property fails. Has the method been moved or deleted?

**Comment by wagenaartje** [comment]
It has been changed to lowercase: methods.mutation.FFW.

**Comment by tracycollins** [comment]
Thanks
