### ISSUE TITLE
Error: Dataset input/output size should be same as network input/output size!

### ISSUE THREAD

**Issue by Hunchmun** [wagenaartje/neataptic#41]
Apologies if I'm making a silly mistake somewhere,

I'm using the following network generation settings for a NARX network:
```
var settings = {
    inputSize: 4,
    hiddenLayers: 5,
    outputSizes: 1,
    previousInput: 3,
    previousOutput: 3
};
```

With the following test data:
```
  { input: [ 0.0199, 0.01956, 0.01976, 0.01963 ], output: [ 1 ] },
// About 400 in length
```

Any help/direction would be appreciated

**Comment by wagenaartje** [comment]
The `settings` should not be given as an object. It's just a regular constructor ([docs](https://wagenaartje.github.io/neataptic/docs/builtins/narx/)):

```js
var net = new architect.NARX(inputSize, hiddenLayers, outputSize, previousInput, previousOutput);
```

So for your desired options, you have to create the network as follows:

```js
var net= new neataptic.architect.NARX(4, 5, 1, 3, 3);
```

So this code should work for you:

```js
var net = new neataptic.architect.NARX(4, 5, 1, 3, 3);
var dataSet = [{ input: [ 0.0199, 0.01956, 0.01976, 0.01963 ], output: [ 1 ] }];

net.train(dataSet, {
  iterations: 10,
  log: 1
});
```

[Run it here](https://jsfiddle.net/wagenaartje/ev1o0ftL/2/)

Sorry for any confusion, if there is a specific part in the documentation that confuses you please let me know so I can change it.

**Comment by Hunchmun** [comment]
Sorry, thanks for your prompt response, made me realise a mistake I had made with my own variable names,

All sorted now, sorry for bothering you, thanks for making such an awesome library!
