### ISSUE TITLE
Error: Cannot find module './neataptic' in worker.js

### ISSUE THREAD

**Issue by tracycollins** [wagenaartje/neataptic#56]
Not sure if I'm requiring the neataptic module correctly.

I fixed this by changing the line in neataptic/src/multithreading/workers/node/worker.js from:

`var { multi, methods } = require('./neataptic');`

to 

`var { multi, methods } = require('../../../neataptic');`

**Comment by wagenaartje** [comment]
I figure it should be 

```js
var { multi, methods } = require(path.join(__dirname, '/neataptic'));
``` 

I'll fix this soon.

**Comment by tracycollins** [comment]
I have it installed locally, i.e.:

/home/tc/myModule/node_modules/neataptic

**Comment by kristiany** [comment]
I get the same. Fixed it by installing `neataptic` globally and changing the import in the above mentioned file to 

```javascript
var { multi, methods } = require('neataptic');
```

**Comment by wagenaartje** [comment]
This was definitely a bug. Thanks for pointing it out @tracycollins. I applied your fix in the latest commit to fix the issue.

Thanks!
