### ISSUE TITLE
Node require

### ISSUE THREAD

**Issue by liebig** [wagenaartje/neataptic#59]
I am sorry, but I don't get Neataptic running with node:
Console
```npm install neataptic```
app.js
```js
var neataptic = require('neataptic');
```
Error
```
SyntaxError: Unexpected token function
c:\neat\node_modules\neataptic\src\architecture\network.js:831
  evolve: async function (set, options) {
                ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\neat\node_modules\neataptic\src\architecture\architect.js:3:15)
```
network.js:831
```js
  evolve: async function (set, options) {
```

**Comment by wagenaartje** [comment]
Neataptic requires Node `v8` or higher (I belive everything from `v7.6` is also sufficient). What Node version are you running?

**Comment by skaraman** [comment]
you need to add `babel-transform-runtime`
https://babeljs.io/docs/plugins/transform-runtime/

**Comment by liebig** [comment]
I had version ```v6.11.1``` and updated to ```v8.4.0```. Now everything is working. Thank you for the reply. Maybe you can add this information to the README file?

**Comment by wagenaartje** [comment]
Thanks for the tip @liebig , I added it to the README file. 

@skaraman I believe most, [if not all](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Statements/async_function), support async. And Node has been supporting it for quite some while now, so I don't think it is necessary to use Babel. (Maybe if I use some other ES7/ES8 code in the future)
