### ISSUE TITLE
A possibility to control the populations complexity in NEAT evolution.

### ISSUE THREAD

**Issue by alaa-eddine** [wagenaartje/neataptic#61]
Hi, 
It's been a while I'm looking for a JS Neat library and I just stumbled upon neataptic, it's amazing :)

I have a suggestion: 
It'll be interesting to have a way to control the networks complexity in NEAT evolution, as sometimes we want to find a solution but we don't want it to have more than certain number of Nodes/connections/gates ...

I see two possibilities to do that : 
1 - adding three new options to Neat class : maxNodes, maxConns and maxGates, and add an optional marameter in Network.prototype.mutate to pass Neat object so that the code can have access to Neat options and exit Add_Node, Add_Connection and Add_Gate if they exeed the limit.

2 - instead of selecting a random mutation method in Neat.prototype.mutate
```
var mutationMethod = this.mutation[Math.floor(Math.random() * this.mutation.length)];
```
use a custom function to select the mutationMethod which will be a random by default.

if you think that one of the modifications (or both) are interesting I can propose a PR for one of them or both.

**Comment by wagenaartje** [comment]
I really like the first idea! That also prevents overfitting. I'm not sure what you mean with the second one, but i'm guessing moving the random selection to a seperate function. Please enlighten me what you mean exactly!

I think you could combine the two ideas: create a seperate function in the ` Neat.prototype`  object that returns a random mutation method. But if ` maxNodes`  is exceeded, never return `mutation.ADD_CONN`  for example. That way no extra option for `Neat.protoype.mutate`  is needed. 

But feel free to implement it however you want, and then we'll review the PR :+1:

**Comment by alaa-eddine** [comment]
well the first proposition is more specific to my main request (ie. controlling the network complexity), while the second one gives more flexibility and better control over the mutation functions, it would cover more cases.

I think I'll prepare and test an implementation of my second proposition, and make a PR. as you said, it's less interfering with the existing code, and provide more freedom to the developer.
