### ISSUE TITLE
Extended target seeking demo :-)

### ISSUE THREAD

**Issue by corpr8** [wagenaartje/neataptic#64]
I added:

1) Each ship has it's own acceleration.
2) When evolution occurs, the ships are left in the same position but get a new brain.
3) Changed the colours to match the voices in my head. 

I've seen this converge on a solution in 61 generations.
https://github.com/corpr8/neataptic-targetseeking-tron

**Comment by AlexisTM** [comment]
Nice work!

Yet, I got had to wait a lot of generations before solution. I noticed the players were not gaining complexity. 

Therefore, I did a simple test. Editing the neataptic library to allow multiple mutations and it now gives a solution terribly fast.

**Comment by corpr8** [comment]
Cool - what did you change? Please paste the fragment :-)

**Comment by AlexisTM** [comment]
I copied pasted multiple times those lines: 

https://github.com/wagenaartje/neataptic/blob/34cf15c40265c9e9c7f63162234881c5c0da039c/dist/neataptic.js#L2887-L2888

Therefore, when it mutates, it mutates multiple times. 

Yet, the network complexity gets a solution fast, but after getting a solution, the complexity continues to increase pretty fast.

**Comment by corpr8** [comment]
Thanks! :-)

**Comment by corpr8** [comment]
I got the network to converge in approx 60 generations.

I extended the demo:
1) removed X/Y limits
2) implemented variable mutation (mutation decays as the network average tends toward a threshold)

**Comment by wagenaartje** [comment]
That's a very fluid demo you made. I have just seen it converge, it works like a charm. If you don't mind, could I link it in the `README.md` of the original [`target-seeking-ai`](https://github.com/wagenaartje/target-seeking-ai) repo or on the website (https://wagenaartje.github.io/neataptic/)

**Comment by corpr8** [comment]
I would absolutely love that!

I added a nodejs server and a test harness which automatically monitors convergence and runs some stats :-)

Average convergence: 74 generations right now!

**Comment by wagenaartje** [comment]
Before I go and add it to the readme and website, could you consider using [Github pages](https://pages.github.com/). This allows people interested in your project to run it from a website instead of downloading the actual repo.

**Comment by corpr8** [comment]
Sure thing. I'll work on it...

**Comment by corpr8** [comment]
Ok - it's done:

Basic simulation is here:
https://corpr8.github.io/neataptic-targetseeking-tron/index.html

Simulation with statistics here:
https://corpr8.github.io/neataptic-targetseeking-tron/testHarness.html

:-)

**Comment by wagenaartje** [comment]
I added it to the `target-seeking-ai` repo in the `README.md`. It should also appear on Neataptic's website when a new version is published.

**Comment by corpr8** [comment]
:)
