### ISSUE TITLE
Reference error, architect is not defined 

### ISSUE THREAD

**Issue by sbatir** [wagenaartje/neataptic#67]
Hi there, Apologies if this is a little basic, but I'm trying out the tutorials and get the following error. I've globally installed neataptic, and I have the latest version of Node.js and npm. 

`ReferenceError: architect is not defined
    at Object.<anonymous> (/path/to/trainingtutorial/training_tut.js:9:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
`

**Comment by wagenaartje** [comment]
How are you calling architect?

It haa to be called as neataptic.architect

**Comment by sbatir** [comment]
I was just following the tutorial here: https://wagenaartje.github.io/neataptic/docs/tutorials/training/

So I had the code below, but it gave a reference Error. I also changed it after reading your comment to : 
`var myNetwork = neataptic.architect.Perceptron(2,3,1); 
`
Both still return either the original ReferenceError. Am I missing a require statement at the top? I've tried those too, but it doesn't seem to change anything. 

`var myTrainingSet = [  //The XOR network. 
    {input: [0,0], output: [0]},
    {input: [0,1], output: [1]},
    {input: [1,0], output: [1]},
    {input: [1,1], output: [0]}    
]; 

// Two input, 3 layers, 1 output. 
var myNetwork = architect.Perceptron(2,3,1); 

myNetwork.train(myTrainingSet, {
    log: 10,
    error: 0.03,
    iterations: 700,
    rate: 0.3
}); 
`

**Comment by wagenaartje** [comment]
Strange. You should definitely require Neataptic though. Could you check if the following code works:

```js
const { architect } = require('neataptic');
var myTrainingSet = [
  {input: [0,0], output: [0]},
  {input: [0,1], output: [1]},
  {input: [1,0], output: [1]},
  {input: [1,1], output: [0]}
];

// Two input, 3 layers, 1 output.
var myNetwork = architect.Perceptron(2, 3, 1);

myNetwork.train(myTrainingSet, {
  log: 10,
  error: 0.03,
  iterations: 700,
  rate: 0.3
});
```

**Comment by sbatir** [comment]
Great! It works now. I didn't realize that was a necessary line, and that you needed to link it to a const variable "architect." Do you do this manually for most objects within Neataptic? Thanks so much.

**Comment by wagenaartje** [comment]
No `const` is completely unnecessary. You can easily replace it with `var`. The difference is that once you have assigned a `const`, you can't re-assign the variable name.

Glad it helped!
