### ISSUE TITLE
Documentation nav sidebar doesn't scroll

### ISSUE THREAD

**Issue by spiffytech** [wagenaartje/neataptic#73]
The [Docs](https://wagenaartje.github.io/neataptic/docs/) page has a nav sidebar, but it cuts off at the bottom. I cannot scroll the navbar down to reach all of the entries.

**Comment by stevn999** [comment]
Same issue, can be fixed with something similar to [this](https://stackoverflow.com/questions/34728883/fixed-height-scrollable-div-inside-of-a-bootstrap-3-column).
