### ISSUE TITLE
Ability to run neataptic in a browser's web worker

### ISSUE THREAD

**Issue by aaronshaf** [wagenaartje/neataptic#75]
As of now it [assumes](https://github.com/wagenaartje/neataptic/blob/8492952268042d4db6d95617e59387ad62eb02d3/src/architecture/network.js) node in the absence of `window`:

```
    var threads = options.threads;
    if (typeof threads === 'undefined') {
      if (typeof window === 'undefined') { // Node.js
        threads = require('os').cpus().length;
      } else { // Browser
        threads = navigator.hardwareConcurrency;
      }
    }
```

**Comment by wagenaartje** [comment]
Good catch. I'll rewrite this into actually detecting `Node.js` instead of `not Node.js` using:

```js
(typeof process !== 'undefined') && (process.release.name === 'node')
```

**Comment by wagenaartje** [comment]
So I started fixing this until I got some weird errors involving `ReferenceError: Worker is not defined`.

Is it possible to create workers from inside workers in the first place?
