### ISSUE TITLE
throw new Error('No input or output size given');

### ISSUE THREAD

**Issue by antonhauff** [wagenaartje/neataptic#88]
Hi. I wanted to implement the following task. I have a function which input gives 0 or 1. The output it gives also 0 or 1. You want to predict that to apply to the input 0 or 1 to the output is always 1. Using NARX networks I wanted to forecast. Is it possible? 
As soon as I started implementing the code, I had the following error: throw new Error('No input or output size given');
What to look for code for this network for prediction?

**Comment by wagenaartje** [comment]
What does your code look like? Share and i'll point out the mistakes!

**Comment by antonhauff** [comment]
Thanks, I already figured out.

**Comment by antonhauff** [comment]
Thanks, I already figured out.
