### ISSUE TITLE
Add LSTM options info to wiki

### ISSUE THREAD

**Issue by basickarl** [wagenaartje/neataptic#9]
I would of done a pull request but you can't do pull requests to the wiki unfortunately. Wiki under Architects LSTM.

// more wiki...
Also you can set many layers of memory blocks:
```
var myLSTM = new Architect.LSTM(2,4,4,4,1);
```
You can pass options if desired like so:
```
var options = {
  memoryToMemory: false,      // default is false
  outputToMemory: false,      // default is false
  outputToGates: false,       // default is false
  inputToOutput: true         // default is true
};
var myLSTM = new Architect.LSTM(2,4,4,4,1,options);
```
// more wiki...

**Comment by wagenaartje** [comment]
Thank you very much for this contribution. I have changed the wiki settings so everybody can contribute to the wiki. I'll leave it that way for some time to see how it turns out.
