### ISSUE TITLE
NEAT to solve XOR

### ISSUE THREAD

**Issue by FLYBYME** [wagenaartje/neataptic#96]
Can you use the NEAT process to solve the XOR problem.

So what im asking is instead of training the network on a dataset you use the "mutation" thing to test the outputs to see if they are correct.

If so can someone talk me through it.
I  have given it a shot but I keep getting number from `this.brain.activate(input)` that are well above 1 and below 0

I already have a dataset that I can train the network on but I want to see if I can mutate the network into on that is the same or even better then one that was trained.

**Comment by wagenaartje** [comment]
There is an example first thing on the [readme](https://github.com/wagenaartje/neataptic):

```js
// this network learns the XOR gate (through neuro-evolution)
var network = new Network(2,1);

var trainingSet = [
  { input: [0,0], output: [0] },
  { input: [0,1], output: [1] },
  { input: [1,0], output: [1] },
  { input: [1,1], output: [0] }
];

await network.evolve(trainingSet, {
  equal: true,
  error: 0.03
 });
```

The thing it it looks like the code above 'trains' the network, but it is actually running a genetic algorithm that evolves genomes to perform well on the data set through _mutation_, like you want.

If you have any more specific questions, provide some snippets of your code so I can see exactly what you are trying to accomplish.
