### ISSUE TITLE
"Crossover playground" dead link from README.md

### ISSUE THREAD

**Issue by Gustavo6046** [wagenaartje/neataptic#99]
In the README file, there is a list of examples of `neataptic` usage. One of them is a 'crossover playground' that, unfortunately, currently returns the `404` code. I'd still be interested in seeing it, though.

**Comment by wagenaartje** [comment]
Thanks for the tip. Unfortunately the crossover playground was removed, but there is still a regular 'playground' where you can experiment with network topology: https://wagenaartje.github.io/neataptic/articles/playground/

I updated the link!
